#!/usr/bin/env python

# Meshtastic bridge script
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
from sys import stdin, stdout, argv, exit
from time import sleep
from argparse import ArgumentParser


# tool options
opts = None


def parseargs(args):
    parser = ArgumentParser(prog='chirpy-mesh',
                            description='Bridge from chirpy pipelines to Meshtastic')
    parser.add_argument('--channel', '-c', dest='channel',
                        action='store', default=0,
                        help='Meshtastic channel to listen or send to')
    parser.add_argument('--host', '-H', dest='meshHost',
                        action='store', default=None,
                        help='Host for Meshtastic device')
    parser.add_argument('--port', '-P', dest='meshPort',
                        action='store', default=None,
                        help='Port for Meshtastic device')
    parser.add_argument('--from', '-f', dest='fromMesh',
                        action='store_const', const=True, default=False,
                        help='Bridge messages from Meshtastic')
    parser.add_argument('--all', '-a', dest='showAll',
                        action='store_const', const=True, default=False,
                        help='Pass all messages, recognised or not')
    return parser.parse_args(args)


def onMessage(message):
    """Meshtastic callback for each message.

    We check whethere the message has a type we recognise,
    and if so print it.

    @param message: the JSON message"""
    if chirpy.isObservation(message) or opts.showAll:
        print(json.dumps(message))
        print()
        stdout.flush()
        chirpy.logger.debug("Forwarded message from mesh")
    else:
        chirpy.logger.debug("Dropped non-chirpy message on mesh")


def main():
    global opts

    opts = parseargs(argv[1:])
    if opts.fromMesh:
        if opts.showAll:
            chirpy.logger.info("Bridging all Meshtastic messages to stdout")
        else:
            chirpy.logger.info("Bridging chirpy Meshtastic messages to stdout")

        # read message from Meshtastic and pass through
        chirpy.meshtasticConnect(host=opts.meshHost, port=opts.meshPort, callback=onMessage)
        while True:
            sleep(10000)
    else:
        chirpy.logger.info("Piping messages to Meshtastic")

        # read messages from stdin and re-transmit
        chirpy.meshtasticConnect(host=opts.meshHost, port=opts.meshPort)
        while True:
            msg = chirpy.readJSON()
            if msg is None:
                exit(0)
            chirpy.meshtasticSendMessage(msg)


if __name__ == "__main__":
    main()
