#!/usr/bin/env python

# MQTT logging script
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
import config


def onObservation(observation):
    chirpy.dbRecordObservation(observation)


def main():
    chirpy.mqttConnect(topics={config.mqtt_topic: onObservation})
    chirpy.dbOpenConnection(config.sqlite_db)

    while True:
        pass


if __name__ == "__main__":
    main()
