#!/usr/bin/env python

# Meshtastic bridge script
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
from sys import stdin, stdout, argv, exit
from argparse import ArgumentParser


# tool options
opts = None


def parseargs(args):
    parser = ArgumentParser(prog='chirpy-mesh',
                            description='Bridge from chirpy pipelines to Meshtastic')
    # for now there are no command line options available
    return parser.parse_args(args)


def main():
    global opts

    opts = parseargs(argv[1:])

    # read messages from stdin and re-transmit
    chirpy.meshtasticConnect()
    while True:
        msg = chirpy.readJSON()
        if msg is None:
            exit(0)
        chirpy.meshtasticSendMessage(msg)


if __name__ == "__main__":
    main()
