#!/usr/bin/env python

# MQTT logging script
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
import config
from os.path import exists, isfile
import sqlite3


# Global database connection
connection = None


def onFirstObservation(fn = None):
    global connection

    if fn is None:
        fn = config.sqlite_db

    if exists(fn):
        if not isfile(fn):
            # exists but not a file
            raise ValueError(f"Can't open {fn} as database file")
        else:
            # exists and is file, connect
            connection = sqlite3.connect(fn)
    else:
        # doesn't exist, create
        connection = sqlite3.connect(fn)
        cursor = connection.cursor()
        cursor.execute("CREATE TABLE birds(timestamp, id, confidence, common_name, scientific_name)")


def onObservation(observation):
    global connection

    # create the connection if this is the first observation
    if connection is None:
        onFirstObservation()

    # record the observation
    record = [observation["timestamp"],
              observation["id"],
              observation["confidence"],
              observation["common"],
              observation["sci"] ]
    cursor = connection.cursor()
    cursor.executemany("INSERT INTO birds VALUES(?, ?, ?, ?, ?)", [record])
    connection.commit()


def main():
    chirpy.mqttConnect(topics={config.mqtt_topic: onObservation})

    while True:
        pass


if __name__ == "__main__":
    main()
