#!/usr/bin/env python

# Classification script
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
import numpy as np
from sys import stdin, stdout, argv
import json


# find the project root directory
import os
cwd = os.path.dirname(os.path.realpath(__file__))
rootDir = os.path.dirname(os.path.dirname(cwd))

# find the model files relative to the project root
modelFile = os.path.join(rootDir, "models/audio-model-int8.tflite")
labelFile = os.path.join(rootDir, "models/labels/en_uk.txt")


def main():
    # load the model
    chirpy.loadModel(modelFile)
    chirpy.loadLabels(labelFile)

    while True:
        # read a signal
        sample = chirpy.readJSON()
        if sample is None:
            exit(0)
        chirpy.logger.debug(f"Sample received for {sample['timestamp']}")

        # classify the signal
        segments = chirpy.segment(np.asarray(sample['signal']), sample['sampleRate'], 3, 1)
        prediction = chirpy.classify(segments)
        mli, confidence = chirpy.mostLikelyIndex(prediction)

        if mli is not None:
            # report
            chirpy.printObservation(sample['timestamp'], mli, confidence, sample['nodeIdentifier'])


if __name__ == "__main__":
    main()
