#!/usr/bin/env python

# MQTT bridgescript
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
from sys import stdin, stdout, argv, exit
import json
from argparse import ArgumentParser


# tool options
opts = None


def parseargs(args):
    parser = ArgumentParser(prog='chirpy-mqtt',
                            description='Bridge from chirpy pipelines to MQTT')
    parser.add_argument('--from', '-f', dest='fromTopic',
                        action='store', default=None,
                        help='Topic to read messages from')
    parser.add_argument('--to', '-t', dest='toTopic',
                        action='store', default=None,
                        help='Topic to send messages to')
    return parser.parse_args(args)


def onMessage(msg):
    """Print any message received onto stdout.

    :param mesg: the JSON message"""
    if opts.toTopic is None:
        # send message to stdout
        print(json.dumps(msg))
        print()
        stdout.flush()
    else:
        # send message to the specified target topic
        chirpy.mqttSendMessage(msg, opts.toTopic)


def main():
    global opts

    opts = parseargs(argv[1:])
    if opts.fromTopic is None and opts.toTopic is None:
        chirpy.logger.debug("No MQTT topics specified, acting as a pipe")

    topics = None
    if opts.fromTopic is None:
        # read messages from stdin and re-transmit
        chirpy.mqttConnect()
        while True:
            msg = chirpy.readJSON()
            if msg is None:
                exit(0)
            onMessage(msg)
    else:
        # register to receive essages
        topics = {opts.fromTopic: onMessage}
        chirpy.mqttConnect(topics=topics)
        while True:
            pass


if __name__ == "__main__":
    main()
