#!/usr/bin/env python

# Audio sampling script
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
from sys import argv
from datetime import datetime, timedelta
import dateutil
from time import sleep
from argparse import ArgumentParser
from suntime import Sun


sun = Sun(chirpy.config.nodeLatitude, chirpy.config.nodeLongitude)
tz = dateutil.tz.gettz()


def parseargs(args):
    parser = ArgumentParser(prog='chirpy-sample',
                            description='Capture regular audio samples')
    parser.add_argument('--nighttime', '-n', dest='nighttime', action='store_true',
                        help='Stop recording at night-time')
    parser.add_argument('--samples', '-N', dest='samples', action='store',
                        type=int, default=None,
                        help='Take a given number of samples')
    return parser.parse_args(args)


def sample(timestamp):
    """Take a sample and output it.

    :param timestamp: the time of the sample"""
    # load a sample signal
    sig, sampleRate = chirpy.record(chirpy.config.sampleDuration)

    # send the sample to stdout
    #chirpy.printSample(timestamp, chirpy.config.sampleDuration, sig, sampleRate)
    print(f"sample {timestamp}")


def sleepUntil(timestamp):
    """Sleep until the given time.

    :param timestamp: the time to sleep until"""
    now = datetime.now()
    delay = timestamp - now
    chirpy.logger.info(f"Sleeping until {timestamp} (time is now {now})")
    sleep(delay.seconds)


def main():
    opts = parseargs(argv[1:])

    if opts.samples is not None:
        chirpy.logger.info(f"Taking {opts.samples} samples")

    # compute the next sunset or sunrise
    today = datetime.today()
    now = datetime.now()
    offset = timedelta(minutes=chirpy.config.nighttimeOffset)
    sunrise = sun.get_sunrise_time(today, tz) - offset
    sunset = sun.get_sunset_time(today, tz) + offset
    if opts.nighttime:
        if now.timestamp() < sunrise.timestamp():
            # started before sunrise, wait
            sleepUntil(sunrise)

        # log our wakefulness
        chirpy.logger.info(f"Sampling until {sunset} (time is now {now})")

    samplesTaken = 0
    while (opts.samples is None) or (samplesTaken < opts.samples):
        now = datetime.now()

        if opts.nighttime:
            # check for night-time
            if now.timestamp() > sunset.timestamp():
                # after sunset, compute tomorrow's sunrise and sunset
                tomorrow = today + timedelta(days=1)
                sunrise = sun.get_sunrise_time(tomorrow, tz) - offset
                sunset = sun.get_sunset_time(tomorrow, tz) + offset

                # pause until sunrise
                sleepUntil(sunrise)
                now = datetime.now()
                chirpy.logger.info(f"Sampling until {sunset} (time is now {now})")

            # take a sample
            sample(now)
        else:
            # collect a sample regardless
            sample(now)

        samplesTaken += 1

    if opts.samples is not None:
        chirpy.logger.info(f"Took {samplesTaken} samples")


if __name__ == "__main__":
    main()
