#!/usr/bin/env python

# Meshtastic bridge script
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
from sys import stdin, stdout, argv, exit
import json
from argparse import ArgumentParser


# tool options
opts = None


def parseargs(args):
    parser = ArgumentParser(prog='chirpy-mt',
                            description='Bridge from chirpy pipelines to Meshtastic')
    parser.add_argument('--to', '-t', dest='toTopic',
                        action='store', default='chirpy/spot',
                        help='Topic to send messages to')
    return parser.parse_args(args)


def onMessage(msg):
    """Print any message received onto stdout.

    :param mesg: the JSON message"""
    else:
        # send message to the specified target topic
        chirpy.mqttSendMessage(msg, opts.toTopic)


def main():
    global opts

    opts = parseargs(argv[1:])

    # read messages from stdin and re-transmit
    chirpy.meshtasticConnect()
    while True:
        msg = chirpy.readJSON()
        if msg is None:
            exit(0)
        shirpy.meshtasticSendMessage(msg, opt.toTopic)


if __name__ == "__main__":
    main()
