#!/usr/bin/env python

# Audio sampling script
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
import config
from datetime import datetime


def main():
    while True:
        # load a sample signal
        timestamp = datetime.now()
        sig, sampleRate = chirpy.record(config.sampleTime)

        # send the sample to stdout
        chirpy.printSample(timestamp, config.sampleTime, sig, sampleRate)


if __name__ == "__main__":
    main()
