#!/usr/bin/env python

# Audio sampling script
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
import os
from datetime import datetime
import dateutil
from suntime import Sun


sun = Sun(chirpy.config.nodeLatitude, chirpy.config.nodeLongitude)
tz = dateutil.tz.gettz()


def withinSampleInterval(timestamp):
    """Test whether the current time is within the sampling time.

    @param timestamp: the time to check
    @returns: True if a sample should be taken"""
    return True


def main():
    while True:
        timestamp = datetime.now()

        if withinSampleInterval(timestamp):
            # load a sample signal
            sig, sampleRate = chirpy.record(chirpy.config.sampleDuration)

            # send the sample to stdout
            chirpy.printSample(timestamp, chirpy.config.sampleDuration, sig, sampleRate)
        else:
            # wait
            pass


if __name__ == "__main__":
    main()
