#!/usr/bin/env python

# Logging script
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
from sys import exit
import json

# find the project root directory
import os
cwd = os.path.dirname(os.path.realpath(__file__))
rootDir = os.path.dirname(os.path.dirname(cwd))

# find the model files relative to the project root
labelFile = os.path.join(rootDir, "models/labels/en_uk.txt")


def main():
    chirpy.loadLabels(labelFile)
    chirpy.dbOpenConnection(chirpy.config.sqlitedb)

    while True:
        observation = chirpy.readJSON()
        if observation is None:
            exit(0)
        chirpy.dbRecordObservation(observation)


if __name__ == "__main__":
    main()
