#!/usr/bin/env python

# Heartbeat generation script
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
from sys import stdout, argv, exit
from time import sleep
from datetime import datetime
import dateutil
import json
from argparse import ArgumentParser


tz = dateutil.tz.gettz()


# tool options
opts = None


def parseargs(args):
    parser = ArgumentParser(prog='chirpy-heartbeat',
                            description='Generate periodic heartbeat messages')
    parser.add_argument('--interval', '-t', dest='heartbeat',
                        action='store', default=chirpy.config.heartbeat,
                        help=f'Heartbeat interval in seconds (default {chirpy.config.heartbeat}s')
    return parser.parse_args(args)


def heartbeat():
    """Return a heartbeat message."""

    # mask-out sub-seconds in the timestamp
    ts = datetime.now().replace(microsecond=0)

    return {'type': chirpy.heartbeatType,
            'timestamp': ts.isoformat(),
            'nodeIdentifier': chirpy.config.nodeIdentifier}


def main():
    global opts

    opts = parseargs(argv[1:])
    t = int(opts.heartbeat)
    chirpy.logger.info(f"Starting heartbeats every {t}s")

    while(True):
        hb = heartbeat()
        print(json.dumps(hb))
        print()
        stdout.flush()

        sleep(t)


if __name__ == "__main__":
    main()
