#!/usr/bin/env python

# MQTT logging script
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import json
import chirpy

# find the project root directory
import os
cwd = os.path.dirname(os.path.realpath(__file__))
rootDir = os.path.dirname(os.path.dirname(cwd))

# find the model files relative to the project root
labelFile = os.path.join(rootDir, "models/labels/en_uk.txt")


def onObservation(observation):
    # we need to open the connection here, not in the main routine,
    # because SQLite databases can only be used from the thread that
    # creates them
    chirpy.dbOpenConnection(chirpy.config.sqlitedb)

    chirpy.dbRecordObservation(observation)
    chirpy.logger.debug(f"Recorded observation {json.dumps(observation)}")


def main():
    chirpy.loadLabels(labelFile)
    chirpy.mqttConnect(topics={chirpy.config.mqttTopic['observation']: onObservation})

    while True:
        pass


if __name__ == "__main__":
    main()
