#!/usr/bin/env python

# chirpy command-line recorder/player to test the sound card
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this software. If not, see <http://www.gnu.org/licenses/gpl.html>.

import chirpy
import sounddevice as sd
import threading


data = None
current_frame = 0
event = threading.Event()


def callback(outdata, frames, time, status):
    global current_frame

    if status:
        print(status)
    chunksize = min(len(data) - current_frame, frames)
    outdata[:chunksize] = data[current_frame:current_frame + chunksize]
    if chunksize < frames:
        outdata[chunksize:] = 0
        raise sd.CallbackStop()
    current_frame += chunksize


def main():
    global data

    data, sampleRate = chirpy.record(5)

    stream = sd.OutputStream(samplerate=sampleRate,
                             device=None,
                             channels=1,
                             callback=callback,
                             finished_callback=event.set)
    with stream:
        event.wait()


if __name__ == "__main__":
    main()
