#!/usr/bin/env python

# chirpy command-line recogniser
#
# Copyright (C) 2025 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this software. If not, see <http://www.gnu.org/licenses/gpl.html>.

# find the project root directory
import os
cwd = os.path.dirname(os.path.realpath(__file__))
rootDir = os.path.dirname(os.path.dirname(cwd))

# load everything else
import chirpy
from datetime import datetime
from sys import argv

# find the model files relative to the project root
modelFile = os.path.join(rootDir, "models/audio-model-int8.tflite")
labelFile = os.path.join(rootDir, "models/labels/en_uk.txt")


def main(sampleFile):
    # load the model
    chirpy.loadModel(modelFile)
    chirpy.loadLabels(labelFile)
    chirpy.mqttConnect()

    # load a signal
    now = datetime.now()
    sig, sampleRate = chirpy.load(sampleFile)
    loadTime = datetime.now()

    # classify the signal
    segments = chirpy.segment(sig, sampleRate, 3, 1)
    segmentTime = datetime.now()
    prediction = chirpy.classify(segments)
    classifyTime = datetime.now()
    mli, confidence = chirpy.mostLikelyIndex(prediction)

    # report
    observation = chirpy.makeObservation(mli, confidence)
    print(chirpy.identify(mli)[1])
    print(confidence)
    print(observation)

    print(f"Load time = {loadTime - now}")
    print(f"Signal segmantation time = {segmentTime - loadTime}")
    print(f"Classification time = {classifyTime - segmentTime}")

    chirpy.mqttReportObservation(observation)


if __name__ == "__main__":
    sampleFile = argv[1]
    main(sampleFile)
