#!/usr/bin/env python

# chirpy observations listing
#
# Copyright (C) 2025--2026 Simon Dobson
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License

import chirpy
import config
from datetime import datetime, timedelta


def main():
    chirpy.dbOpenConnection(config.sqlite_db)

    now = datetime.now()
    then = now - timedelta(days=20)
    observations = chirpy.dbAllObservationsBetween(then)
    print(observations)


if __name__ == "__main__":
    main()
